# environment
env_name: walker/walk # this item will be ignored when given domain_name and task_name 
domain_name: walker
task_step: 200
pre_transform_image_size: 84
image_size: 84
action_repeat: 1
frame_stack: 1

pos_dim: [5]
action_shape: 2
lidar_shape: [1,360]
# replay buffer
replay_buffer_capacity: 50000
# train
agent: mib # 'curl_sac' or 'spr_sac' or 'cycdm_sac'
init_steps: 1000
task_steps: 200

num_env_steps: 50200 # 500100
batch_size: 64
hidden_dim: 1024
# eval
eval_freq: 1000
num_eval_episodes: 10
# critic
critic_lr: 1e-3
critic_beta: 0.9
critic_tau: 0.01
critic_target_update_freq: 2
# actor
actor_lr: 1e-3
actor_beta: 0.9
actor_log_std_min: -10
actor_log_std_max: 2
actor_update_freq: 2
# encoder
encoder_type: pixel
encoder_feature_dim: 50
encoder_lr: 2e-4
encoder_tau: 0.05
num_layers: 4
num_filters: 32
curl_latent_dim: 128
# sac
discount: 0.99
init_temperature: 0.1
alpha_lr: 1e-4
alpha_beta: 0.5
# cycdm

jumps: 1
transition_model_type: 'deterministic'
transition_model_layer_width: 128
latent_dim: 100
auxiliary_task_batch_size: 64
time_offset: 0
momentum_tau: 0.05
aug_prob: 1.0
num_aug_actions: 10
loss_space: y
bp_mode: gt # 'detach' or 'esti' or 'hybrid' or 'gt'
cycle_steps: 6
cycle_mode: fp+cycle # 'fp'(SPR) or 'fp+cycle'(PlayVirtual) or 'fp+bp+cycle'
fp_loss_weight: 1.0
bp_loss_weight: 1.0
rc_loss_weight: 0.0
vc_loss_weight: 1.0
reward_loss_weight: 0.0
auxiliary_task_lr: 2e-4
# misc
seed: 0
gpuid: 0
seed_and_gpuid: [1234, 0] # this item will be ignored when given seed and gpuid
work_dir: ./cycdm_runs
save_tb: False
save_buffer: false
save_video: false
save_model: true
detach_encoder: false
# log
log_interval: 1000
# wandb
wandb: false
